services:
  - type: web
    name: video-subtitler-flask
    env: python
    region: oregon
    pythonVersion: 3.10  # <--- this must be here, directly under the service

    buildCommand: |
      pip install -r requirements.txt
      python -c "import whisper; whisper.load_model('small'); print('Whisper model downloaded during build.')"

    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app

    healthCheckPath: /

    envVars:
      - key: OPENROUTER_API_KEY
      - key: PERSISTENT_STORAGE_ROOT
        value: /var/data

    disk:
      name: app-persistent-storage
      mountPath: /var/data
