name: Deploy to Azure App Service

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AZURE_WEBAPP_NAME: video-subtitler-app    # Change this to your app name
  AZURE_WEBAPP_PACKAGE_PATH: '.'           # Path to your application code
  PYTHON_VERSION: '3.10'                   # Python version to use

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            .
            !venv/
            !.git/
            !__pycache__/
            !*.pyc

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app
          path: .

      
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ai-video-subtitler
          package: .

  deploy-oidc:
    name: Deploy to Azure Web App using OIDC
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Azure with OIDC
        uses: azure/login@v1
        with:
          client-id: 27f7413a-ee17-41f8-94ff-674124cd25d5
          tenant-id: 90a7916b-fe60-4d09-b7c2-44b0971012ff
          subscription-id: 2d04254f-ca00-4823-ba1c-6946f86900b8

      


