name: Deploy to Azure App Service using OIDC

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

env:
  AZURE_WEBAPP_NAME: ai-video-subtitler          # ✅ your web app name
  AZURE_WEBAPP_PACKAGE_PATH: '.'                # Path to app
  PYTHON_VERSION: '3.10'                        # Python version

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Azure Login via OIDC
        uses: azure/login@v1
        with:
          client-id: 27f7413a-ee17-41f8-94ff-674124cd25d5  # ✅ App Registration Client ID
          tenant-id: 90a7916b-fe60-4d09-b7c2-44b0971012ff  # ✅ Azure Tenant ID
          subscription-id: 2d04254f-ca00-4823-ba1c-6946f86900b8

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
